export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_AVATARS_PENDING = 'REQUEST_AVATARS_PENDING';
export const REQUEST_AVATARS_SUCCESS = 'REQUEST_AVATARS_SUCCESS';
export const REQUEST_AVATARS_FAILED = 'REQUEST_AVATARS_FAILED';